name = "CartLift Analytics"
type = "web_pixel_extension"
uid = "0d11b440-6461-3dbe-8ad0-baf51938940b32241d01"
runtime_context = "strict"

[customer_privacy]
analytics = true
marketing = false
preferences = false
sale_of_data = "disabled"

[settings]
type = "object"

[settings.fields.endpoint]
name = "Analytics endpoint"
description = "CartLift analytics endpoint used by the web pixel."
type = "single_line_text_field"
validations = [
  { name = "min", value = "1" }
]

[capabilities]
network_access = true
